[package]
name = "cache-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
